pipeline {
    agent {
        label 'docker-agent'
    }
    stages {
        stage('Checkout code and prepare environment') {
            steps {
                sh '''
                cd Chapter08/sample1
                chmod +x gradlew
                '''
            }
        }
        stage('Unit testing for all branches') {
            steps {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    sh '''
                    cd Chapter08/sample1
                    ./gradlew test
                    '''
                }
            }
        }
        stage('Code coverage for master only') {
            when {
                branch 'master'
            }
            steps {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    sh '''
                    cd Chapter08/sample1
                    ./gradlew test jacocoTestCoverageVerification
                    '''
                }
            }
        }
        stage('Static code analysis for all branches') {
            steps {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    sh '''
                    cd Chapter08/sample1
                    ./gradlew checkstyleTest
                    '''
                }
            }
            post {
                always {
                    publishHTML (target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                        reportFiles: 'test.html',
                        reportName: "Checkstyle Report",
                        keepAll: true
                    ])
                }
            }
        }
        stage('Jacoco report') {
            steps {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    sh '''
                    cd Chapter08/sample1
                    ./gradlew jacocoTestReport
                    '''
                }
            }
            post {
                always {
                    publishHTML (target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        reportDir: 'Chapter08/sample1/build/reports/jacoco/test/html',
                        reportFiles: 'index.html',
                        reportName: "Jacoco Report",
                        keepAll: true
                    ])
                }
            }
        }
    }
    post {
        success {
            echo "tests pass!"
        }
        failure {
            echo "tests fail!"
        }
    }
}
