pipeline {
    agent {
        label 'docker-agent'
    }
    stages {
        stage('Checkout code and prepare environment') {
            steps {
                git url: 'https://github.com/varsha-rav/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
                sh '''
                cd Chapter08/sample1
                chmod +x gradlew
                '''
            }
        }
        stage("Unit test") {
            steps {
                sh '''
                cd Chapter08/sample1
                ./gradlew test
                '''
            }
        }
        stage('Running test coverage') {
            when {
                changeset "**/*.java"
            }
            steps {
                sh '''
                cd Chapter08/sample1
                ./gradlew test jacocoTestCoverageVerification
                '''
            }
        }
        stage('Checktyle - static code analysis') {
            when {
                changeset "**/*.java"
            }
            steps {
                sh '''
                cd Chapter08/sample1
                ./gradlew checkstyleTest
                '''
            }
            post {
                always {
                publishHTML (target: [
                    reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                    reportFiles: 'test.html',
                    reportName: "jacoco checkstyle",
                    keepAll: true
                ])
                }
            }
        }
    }
    post {
        success {
            echo "pipeline ran perfectly"
        }
        failure {
            echo "pipeline failed"
        }
    }
}
