pipeline {
    agent none
    environment {
        REGISTRY = 'localhost:5001'
        IMAGE    = 'calculator'
        TAG      = "${BUILD_NUMBER}"
        TOPIC    = 'ci.images'
        BROKER   = 'week9-kafka:29092'
    }
    stages {
        stage('Build & push image') {
            agent { label 'docker-agent' }
            steps {
                sh '''
                    docker build -t ${REGISTRY}/${IMAGE}:${TAG} week9/app
                    docker push ${REGISTRY}/${IMAGE}:${TAG}
                '''
            }
        }
        stage('Announce to Kafka') {
            agent {
                docker {
                    image 'localhost:5001/kafka-python:1'
                    args '--network week9_default'
                }
            }
            steps {
                sh 'python week9/publish_event.py'
            }
        }
    }
}